# flake8: noqa
from .home import Home
from .login_admin import LoginAdmin
from .catalogo_admin import CatalogoAdmin
from .cadastrar import Cadastrar
from .adocoes_admin import AdocoesAdmin
from .cadastro_animais_admin import CadastroAnimaisAdmin
from .formularios_admin import FormulariosAdmin
from .login_user import LoginUser
from .formulario_adocao import FormularioAdocao
from .animais_disponiveis import AnimaisDisponiveis
from .editar_animal import EditarAnimal
from .excluir_foto import ExcluirFoto
from .animais_disponiveis_user import AnimaisDisponiveisUser
from .formulario_adocao_user import FormularioAdocaoUser
from .logout import Logout
from .adotar_animal import AdotarAnimal
from .cancelar_adocao import CancelarAdocao
from .aprovar_formulario import AprovarFormulario
