# Generated by Django 4.2.20 on 2025-03-18 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("login", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("especie", models.CharField(max_length=50)),
                ("idade", models.IntegerField()),
                ("porte", models.CharField(max_length=50)),
                ("descricao", models.TextField()),
                (
                    "status_adocao",
                    models.CharField(
                        blank=True,
                        choices=[("A", "Adotado"), ("D", "Disponível")],
                        default="D",
                        max_length=20,
                    ),
                ),
                ("raca", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100, unique=True)),
                ("senha", models.CharField(max_length=128)),
                ("cpf", models.CharField(max_length=14, unique=True)),
                ("data_nascimento", models.DateField()),
                ("telefone", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Foto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.BinaryField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animais",
                        to="acapra.animal",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormularioAdocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_envio", models.DateField()),
                ("todos_concordam", models.BooleanField()),
                ("outros_animais", models.TextField()),
                ("tipo_residencia", models.CharField(max_length=30)),
                ("residencia_telas", models.BooleanField()),
                ("animal_acesso_rua", models.BooleanField()),
                ("endereco_completo", models.BooleanField()),
                ("renda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("manter_animal", models.BooleanField()),
                ("castracao_vacinacao", models.BooleanField()),
                ("taxa_adocao", models.BooleanField()),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animais_formulario_adocao",
                        to="acapra.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_formulario",
                        to="acapra.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoFormulario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_documento", models.CharField(max_length=30)),
                ("arquivo", models.BinaryField()),
                (
                    "formulario_adocao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formularios",
                        to="acapra.formularioadocao",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Adocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_adocao", models.DateField()),
                (
                    "status_adocao",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "Aprovada"),
                            ("P", "Pendente"),
                            ("R", "Reprovada"),
                        ],
                        default="P",
                        max_length=20,
                    ),
                ),
                (
                    "animal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animais_adocao",
                        to="acapra.animal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_adocao",
                        to="acapra.user",
                    ),
                ),
            ],
        ),
    ]
