# Generated by Django 4.2.20 on 2025-03-19 00:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foto",
            name="image",
        ),
        migrations.AddField(
            model_name="foto",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="fotos_animais/"),
        ),
        migrations.AlterField(
            model_name="documentoformulario",
            name="arquivo",
            field=models.ImageField(blank=True, null=True, upload_to="documentos/"),
        ),
    ]
