# Generated by Django 4.2.20 on 2025-04-03 16:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0002_remove_foto_image_foto_imagem_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Admin",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="status_adocao",
        ),
    ]
