# Generated by Django 4.2.20 on 2025-05-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0003_delete_admin_remove_animal_status_adocao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="animal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fotos",
                to="acapra.animal",
            ),
        ),
    ]
