# Generated by Django 4.2.20 on 2025-05-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0004_alter_foto_animal"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="status_adocao",
            field=models.CharField(
                blank=True, choices=[("A", "Adotado"), ("D", "Disponível")], default="D"
            ),
        ),
    ]
