# Generated by Django 4.2.20 on 2025-05-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0005_animal_status_adocao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="especie",
            field=models.CharField(
                choices=[("Gato", "Gato"), ("Cachorro", "Cachorro")], max_length=50
            ),
        ),
    ]
