# Generated by Django 4.2.20 on 2025-05-26 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0006_alter_animal_especie"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentoformulario",
            name="tipo_documento",
        ),
        migrations.AlterField(
            model_name="documentoformulario",
            name="formulario_adocao",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documentos",
                to="acapra.formularioadocao",
            ),
        ),
        migrations.AlterField(
            model_name="formularioadocao",
            name="endereco_completo",
            field=models.CharField(max_length=200),
        ),
    ]
