# Generated by Django 4.2.20 on 2025-08-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0007_remove_documentoformulario_tipo_documento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="doenca",
            field=models.CharField(default="Nenhuma"),
        ),
        migrations.AddField(
            model_name="animal",
            name="observacao",
            field=models.TextField(default="Nenhuma"),
        ),
        migrations.AddField(
            model_name="animal",
            name="vacina",
            field=models.CharField(
                default="Nenhuma", help_text="Separar vacina por ;", max_length=100
            ),
        ),
    ]
