# Generated by Django 5.2.5 on 2025-08-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0008_animal_doenca_animal_observacao_animal_vacina"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="porte",
            field=models.CharField(
                choices=[
                    ("Pequeno", "Pequeno"),
                    ("Medio", "Medio"),
                    ("Grande", "Grande"),
                ],
                max_length=50,
            ),
        ),
    ]
