# Generated by Django 4.2.20 on 2025-10-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0009_alter_animal_porte_alter_animal_raca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="descricao",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="doenca",
            field=models.CharField(blank=True, default="Nenhuma"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="idade",
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name="animal",
            name="observacao",
            field=models.TextField(blank=True, default="Nenhuma"),
        ),
        migrations.AlterField(
            model_name="animal",
            name="porte",
            field=models.CharField(
                choices=[
                    ("Pequeno", "Pequeno"),
                    ("Médio", "Médio"),
                    ("Grande", "Grande"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="raca",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="animal",
            name="vacina",
            field=models.CharField(
                blank=True,
                default="Nenhuma",
                help_text="Separar vacina por ;",
                max_length=100,
            ),
        ),
    ]
