# Generated by Django 4.2.20 on 2025-10-29 00:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("acapra", "0010_alter_animal_descricao_alter_animal_doenca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formularioadocao",
            name="processado",
            field=models.BooleanField(default=False),
        ),
    ]
